- hosts: localhost
  gather_facts: no
  vars_files:
  - aws.yml
  tasks:
  - name:
    pip:
      name: boto3
      state: present
  - name: Creating Security Group for WebServer on AWS
    ec2_group:
      name: SecGrp
      description: Security Group for Web Server allowing port for http and ssh
      region: eu-central-1
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ security_key }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
  - name: launching ec2 instance for builder
    ec2:
        key_name: ansec
        instance_type: t2.micro
        image: ami-0c9354388bb36c088
        wait: true
        group: SecGrp
        count: 1
        vpc_subnet_id: subnet-081298183b5a18fe4
        assign_public_ip: yes
        region: eu-central-1
        state: present
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ security_key }}"
        instance_tags:
          Name: builder
        user_data: |
          #!/bin/sh
          apt update && apt install python maven default-jdk git -y
    register: ec2

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: builder
    loop: "{{ ec2.instances }}"
    delegate_to: localhost

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      state: started
    loop: "{{ ec2.instances }}"

  - name: launching ec2 instance for tomcat
    ec2:
        key_name: ansec
        instance_type: t2.micro
        image: ami-0c9354388bb36c088
        wait: true
        group: SecGrp
        count: 1
        vpc_subnet_id: subnet-081298183b5a18fe4
        assign_public_ip: yes
        region: eu-central-1
        state: present
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ security_key }}"
        instance_tags:
          Name: tomcat
        user_data: |
          #!/bin/sh
          apt update && apt install python tomcat9 git -y
    register: ec2

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: tomcat
    loop: "{{ ec2.instances }}"
    delegate_to: localhost

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      state: started
    loop: "{{ ec2.instances }}"