- hosts: localhost
  gather_facts: no
  vars_files:
  - aws.yml
  tasks:
  - name:
    pip:
      name: boto3
      state: present
  - name: Creating Security Group for WebServer on AWS
    ec2_group:
      name: SecGrp
      description: Security Group for Web Server allowing port for http and ssh
      region: eu-central-1a
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
